// @flow

import DocsDataAttributes from './DocsDataAttributes';
import DocsDecoratorTypes from './DocsDecoratorTypes';
import asElement from './asElement';
import convertImageElementToPlaceholderElement from './convertImageElementToPlaceholderElement';
import getCSSRules from './getCSSRules';
import getSafeDocumentElementFromHTML from './getSafeDocumentElementFromHTML';
import mergeCSSRuleStylesToElement from './mergeCSSRuleStylesToElement';
import uniqueID from './uniqueID';

import type {DocumentLike} from './Types';
import type {CSSRules} from './getCSSRules';

export type SafeHTML = {
  html: string,
  unsafeNodes: Map<string, Node>,
  cssRules: CSSRules,
};

const CHAR_ZERO_WIDTH = '\u200B';

function getSafeHTML(
  html: string,
  domDocument?: ?DocumentLike,
): SafeHTML {
  const documentElement = getSafeDocumentElementFromHTML(html, domDocument);
  const body = documentElement ? documentElement.querySelector('body') : null;
  const ownerDocument: any = body && body.ownerDocument;
  const cssRules = getCSSRules(ownerDocument);
  const unsafeNodes = new Map();
  let safeHTML = '';
  if (body) {
    // The provided chidlren nodes inside the atomic block should never be
    // rendered. Instead, the atomic block should only render with its entity
    // data. Therefore, move the children nodes into the quarantine pool
    // otherwise these chidlren wil be rendered as extra block after the atomic
    // block.
    const quarantine = (node) => {
      const id = uniqueID();
      node.id = id;
      unsafeNodes.set(id, node.cloneNode(true));
      node.innerHTML = CHAR_ZERO_WIDTH;
    };

    const atomicNodes = body.querySelectorAll(
      'figure[' + DocsDataAttributes.ATOMIC_BLOCK_DATA + ']',
    );
    Array.from(atomicNodes).forEach(quarantine);

    // Apply all linked CSS styles to element.
    Array.
      from(body.querySelectorAll('[class]')).
      forEach(mergeCSSRuleStylesToElement.bind(null, cssRules));

    const tableNodes = body.querySelectorAll('table');
    Array.from(tableNodes).forEach(quarantine);

    const mathNodes = body.querySelectorAll(
      'span[' +
      DocsDataAttributes.DECORATOR_TYPE + '="' +
      DocsDecoratorTypes.DOCS_MATH +
      '"]',
    );
    Array.from(mathNodes).forEach(quarantine);

    const imgNodes =  body.querySelectorAll('img');
    Array.from(imgNodes).forEach(convertImageElementToPlaceholderElement);

    // Monkey patch potentially nested lists.
    const listNodes = body.querySelectorAll('ul, ol');
    Array.from(listNodes).forEach(monkeyPatchNestedListElements);

    safeHTML = body.innerHTML;
  }

  return {
    cssRules,
    html: safeHTML,
    unsafeNodes,
  };
}

// This is just a workaround to deal with HTML generated by google doc.
// Somehow in google doc, nested OL or UL elements may not be nested.
// Instead, the nested UI / OL will noyt be nested and rendered with
// margin-left. This function is to enforce the nested structure that can
// be correctly parsed by draft-convert.
function monkeyPatchNestedListElements(el: Element): void {
  const {previousElementSibling, style} = asElement(el);
  if (!style || !previousElementSibling) {
    return;
  }

  const prevNodeName = previousElementSibling.nodeName;
  if (prevNodeName !== 'UL' && prevNodeName !== 'OL') {
    return;
  }

  const items = Array.from(el.children);
  const hasNoMargin = items.some(item => {
    if (item.nodeName !== 'LI' || !item.style.marginLeft) {
      return true;
    }
  });

  if (hasNoMargin) {
    return;
  }
  previousElementSibling.appendChild(el);
}

export default getSafeHTML;
